GET http://localhost:4444
Content-Type: application/json
###

POST http://localhost:4444/init

###
POST http://localhost:4444/login
Content-Type: application/json

{
    "secret": "11111",
    "adminpassword": "cisco"
}

###

GET http://localhost:4444/users

###

GET http://localhost:4444/users/1

###

DELETE http://localhost:4444/users/1
